ARG ARCH=aarch64
ARG REPO=axisecp
ARG RUNTIME_VERSION=1.1.2
ARG RUNTIME_UBUNTU_VERSION=22.04

FROM arm64v8/ubuntu:${RUNTIME_UBUNTU_VERSION} as runtime-image-aarch64
FROM $REPO/acap-runtime:${RUNTIME_VERSION}-${ARCH} as runtime-base

FROM runtime-image-aarch64
WORKDIR /opt/app/
COPY --from=runtime-base /opt/app/*.eap ./
RUN mkdir -p acap_runtime
RUN tar xzf $(ls | grep .eap) -C acap_runtime/

ENTRYPOINT [ "/opt/app/acap_runtime/acapruntime" ]
