ARG ARCH=armv7hf
ARG REPO=axisecp
ARG RUNTIME_VERSION=1.1.1
ARG RUNTIME_UBUNTU_VERSION=22.04

FROM arm64v8/ubuntu:${RUNTIME_UBUNTU_VERSION} as runtime-image-${ARCH}
FROM $REPO/acap-runtime:${RUNTIME_VERSION}-${ARCH} as runtime-base

FROM runtime-image-${ARCH}
WORKDIR /opt/app/
COPY --from=runtime-base /opt/app/*.eap ./
RUN mkdir -p acap_runtime
RUN tar xzf $(ls | grep .eap) -C acap_runtime/

ENTRYPOINT [ "/opt/app/acap_runtime/acapruntime" ]
