ARG ARCH=armv7hf
ARG REPO=axisecp

FROM arm32v7/ubuntu:20.04 as runtime-image-armv7hf
FROM arm64v8/ubuntu:20.04 as runtime-image-aarch64
FROM $REPO/acap-runtime:$ARCH as runtime-base



FROM runtime-image-$ARCH
WORKDIR /opt/app/
COPY --from=runtime-base /opt/app/*.eap ./
RUN mkdir -p acap_runtime
RUN tar xzf $(ls | grep .eap) -C acap_runtime/

ENTRYPOINT [ "/opt/app/acap_runtime/acapruntime" ]
