# syntax=docker/dockerfile:1

ARG ARCH=armv7hf
ARG REPO=axisecp
ARG RUNTIME_VERSION=1.1.2
ARG RUNTIME_UBUNTU_VERSION=22.04

FROM arm32v7/ubuntu:${RUNTIME_UBUNTU_VERSION} as runtime-image-armv7hf
FROM ${REPO}/acap-runtime:${RUNTIME_VERSION}-${ARCH} as runtime-base

FROM runtime-image-armv7hf
WORKDIR /opt/app/

COPY --from=runtime-base /opt/app/*.eap ./
RUN <<EOF
mkdir -p acap_runtime
for f in *.eap; do
    tar -xzf "$f" -C acap_runtime
done
EOF

ENTRYPOINT [ "/opt/app/acap_runtime/acapruntime" ]
