---
name: Update version in ACAP application manifest.json action
description: >
  A local composite action to update the version in a ACAP application
  manifest.json file.

inputs:
  manifest_file:
    description: Path to the manifest file to update.
    required: true
  version:
    description: The new version to update the file with.
    required: true
  version_position:
    description: The position in the file to update.
      Defaults to .acapPackageConf.setup.version.
    default: '.acapPackageConf.setup.version'
    required: false

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        jq '${{ inputs.version_position }} = "${{ inputs.version }}"'
        "$manifest_file" > "$manifest_file".tmp
        mv "$manifest_file".tmp "$manifest_file"
