---
name: 'Update version in manifest action'
description: 'A local composite action to update the version in a manifest file.'

inputs:
  manifest_file:
    description: 'Path to the manifest file to update.'
    required: true
  version:
    description: 'The new version to update the file with.'
    required: true
  version_position:
    description: 'The position in the file to update. Defaults to .acapPackageConf.setup.version.'
    default: '.acapPackageConf.setup.version'

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        tmpfile=$(mktemp)
        manifest_file=${{ inputs.manifest_file }}
        cp "$manifest_file" "$tmpfile"
        jq --arg new_val "${{ inputs.version }}" \
        ${{ inputs.version_position }} |= $new_val' "$tmpfile" >"$manifest_file"
        rm -f "$tmpfile"
