---
name: Run pytest action
description: >
  A local composite action for running a pytest script.

inputs:
  testfile:
    description: Path to the pytest script to run.
    required: true
  requirements_file:
    description: Path to a file listing python packages that are required for
      the pytest script to run. These will be installed before running the
      script. Note that pytest will always be installed.
    default: ''
    required: false
  python-version:
    description: The version of python to use. Default 3.9.
    default: '3.9'
    required: false
  logfile:
    description: Name of logfile produced by the pytest script. Default not set.
      If the test fails and the logfile name is set the file will be saved
      as an artifact.
    default: ''
    required: false

runs:
  using: composite
  steps:
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install pytest and any other required packages
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ "${{ inputs.requirements_file }}" ]
        then
          pip install -r "${{ inputs.requirements_file }}"
        fi
    - name: Run pytest
      shell: bash
      run: |
        pytest -s ${{ inputs.testfile }}
    - name: Upload test log
      uses: actions/upload-artifact@v3
      if: ${{ failure() && inputs.logfile != '' }}
      with:
        name: ${{ inputs.logfile }}
        path: ${{ inputs.logfile }}
