# yamllint disable rule:line-length
---
name: 'Run pytest action'
description: 'A local composite action for running a pytest script towards a remote device.'

inputs:
  testfile:
    description: 'The path to the pytest file to run.'
    required: true
  python-version:
    description: 'The version of python to use. Default 3.9'
    required: false
    default: '3.9'

runs:
  using: 'composite'
  steps:
    - name: Setup python
      # sha for actions/setup-python@v4 at time of commit.
      uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install pytest
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests
    - name: Run pytest
      shell: bash
      run: pytest -s ${{ inputs.testfile }}
    - name: Upload test log
      # sha for actions/upload-artifact@v3 at time of commit
      uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
      if: failure()
      with:
        name: test_log_${{ env.AXIS_TARGET_ARCH }}
        path: test_log_${{ env.AXIS_TARGET_ARCH }}.txt

