#!/bin/bash
# A script to allow building multiple targets from a single Dockerfile such
# that the repository does not need a separate Dockerfile for each build

docker build --target=runtime -f $DOCKERFILE_PATH -t $IMAGE_NAME .
docker build --target=test -f $DOCKERFILE_PATH -t $IMAGE_NAME-test .