#!/bin/bash
# A script to allow building multiple targets from a single Dockerfile such
# that the repository does not need a separate Dockerfile for each build

docker build . -f $DOCKERFILE_PATH -t $IMAGE_NAME
docker build . -f $DOCKERFILE_PATH -t $IMAGE_NAME-test --build-arg TEST=true