#!/bin/bash
# A script to allow building multiple targets from a single Dockerfile such
# that the repository does not need a separate Dockerfile for each build

export TAG=echo $IMAGE_NAME | sed 's/\(.*\)-a.*/\1/'
docker build . -f ${DOCKERFILE_PATH} -t $IMAGE_NAME --build-arg TAG
docker build . -f ${DOCKERFILE_PATH}-containerized -t $IMAGE_NAME-containerized --build-arg TAG
