#!/bin/bash
# A script to allow building multiple targets from a single Dockerfile such
# that the repository does not need a separate Dockerfile for each build

docker push $IMAGE_NAME
docker push $IMAGE_NAME-test