# yamllint disable rule:line-length
---
name: Proto Build Workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Placeholder workflow"
