---
name: temp testing self self-hosted

on: [push]

env:
  ACAP_IMAGE: "axis-ecp/acap-runtime:armv7hf-test"

jobs:
  docker_image:
    name: pull docker image
    runs-on: self-hosted
    steps:
      - run: docker pull ${{ env.ACAP_IMAGE }}
  test_image:
    name: test docker image
    needs: docker_image
    runs-on: self-hosted
    env:
      AXIS_TARGET_USER: "root"
      AXIS_TARGET_PASS: "pass"

    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v3
      -
        name: Setup python
        uses: actions/setup-python@v4
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run test script
        run: pytest -s ./.github/workflows/test_acapruntimetest.py

clean_up:
    name: Cleanup after test run
    if: ${{ always() }}
    needs: [docker_image, test_image]
    runs-on: self-hosted
    steps:
      - run: docker image rm ${{ env.ACAP_IMAGE }}

