# yamllint disable rule:line-length
---
name: Workflow for signing

# Run the workflow on when code is pushed
on:
  push:
  pull_request:
  workflow_dispatch:

# Environment variables that are valid for all jobs
env:
  DOCKER_HUB_REPOSITORY: 'axisecp/acap-runtime'
  ACAP_TO_SIGN_NAME: ACAP_Runtime_1_2_0_aarch64.eap

jobs:
  # Build and run the test suite
  pull_sign_push:
    name: Test signing ACAP Runtime
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [aarch64]

    steps:
      - name: Pull image from DockerHub
        run: |
          docker pull ${{ steps.meta.outputs.full_name }}
      - name: Build and fetch eap-file
        run: |
          docker pull axisecp/acap-runtime:main-aarch64
          docker cp $(docker create ${{ steps.meta.outputs.full_name }}):/opt/app .build
          EAP_PATH=$(find .build -type f -name *.eap)
          echo "EAP_PATH=$EAP_PATH" >> $GITHUB_ENV
          EAP_FILE=$(find .build -type f -printf "%f\n")
          echo "EAP_FILE=$EAP_FILE" >> $GITHUB_ENV
      - name: Sign eap-file
        run: |
          curl -XPOST -H 'accept: */*' -H 'Content-Type: multipart/form-data' -H 'Authorization: Bearer ${{secrets.ACAP_PORTAL_SIGNING_BEARER_TOKEN}}' \
          'https://gw.ext.csi-api.axis.com/ext/acap/admin/application/${{secrets.ACAP_PORTAL_SIGNING_ID}}/sign/binary' -F uploadedFile=@"${{ env.EAP_FILE }}" --output Signed_${{ env.EAP_FILE }}

      - name: Push signed ACAP to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: signed-ACAP
          path: .build/Signed_${{ env.EAP_FILE }}