# yamllint disable rule:line-length
---
name: acap-signing workflow.

# Run the workflow on when code or a semver tag is pushed to main branch,
# and on pull requests towards main branch
on:
  push:
    branches:
      - 'acap-signing'

# Environment variables that are valid for all jobs
env:
  DOCKER_HUB_REPOSITORY: 'axisecp/acap-runtime'

jobs:

  # Build base and containerized images and push to Docker Hub
  # This job is skipped if not on main branch or if build_and_test job has failed
  build_and_push:
    name: Build and push images
    runs-on: ubuntu-latest
    needs: build_and_test
    if: (github.event_name != 'pull_request')
    strategy:
      matrix:
        arch: [armv7hf, aarch64]
    steps:
      - name: Checkout repo
        # sha for actions/checkout@v3 at time of commit.
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Create base image metadata
        id: meta
        uses: ./.github/actions/metadata-action
        with:
          suffix: -${{ matrix.arch }}
          repository: ${{ env.DOCKER_HUB_REPOSITORY }}
          get_version: 'true'
      - name: Get EAP from base image
        id: get_artifact
        run: |
          echo "Full_name ${{ steps.meta.outputs.full_name }}"

          docker cp $(docker create "${{ steps.meta.outputs.full_name }}"):/opt/app .build
          EAP_PATH=$(find .build -type f -name *.eap)
          echo "EAP_PATH=$EAP_PATH" >> $GITHUB_ENV
          EAP_FILE=$(find .build -type f -printf "%f\n")
          echo "EAP_FILE=$EAP_FILE" >> $GITHUB_ENV
      - name: Sign eap-file
        run: |
          cd .build
          curl -XPOST -H 'accept: */*' -H 'Content-Type: multipart/form-data' -H 'Authorization: Bearer ${{secrets.ACAP_PORTAL_SIGNING_BEARER_TOKEN}}' \
          'https://gw.ext.csi-api.axis.com/ext/acap/admin/application/${{secrets.ACAP_PORTAL_SIGNING_ID}}/sign/binary' -F uploadedFile=@"${{ env.EAP_FILE }}" --output Signed_${{ env.EAP_FILE }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: signed-artifact-${{ matrix.arch }}
          path: .build/Signed_${{ env.EAP_FILE }}